### ISSUE TITLE
convert <img> tags to <picture> tags

### ISSUE THREAD

**Issue by justinbacchi73** [FunMan22/SC-Library#125]
any image that we're dynamically sourcing should be placed in a picture element so that we can have a static backup

example:
<picture>
    <source srcset="book-image-00001.jpg"
            media="(min-width: 800px)">
    <img src="/img/default-book.jpg" alt="" />
</picture>

**Comment by FunMan22** [comment]
Change of plans: Just using the onerror event to default to a locally hosted image if the storage fails.

<picture> is more for needed different sources on different browsers or screen sizes.

**Comment by FunMan22** [comment]
implemented to dev with latest commit
