### ISSUE TITLE
figure out what to do about overwriting barcodes

### ISSUE THREAD

**Issue by justinbacchi73** [FunMan22/SC-Library#98]
right now the ui is very clunky. don't want to get rid of the functionality, but needs to be changed somehow

**Comment by FunMan22** [comment]
Solution: Just don't.

We decided that we aren't going to override any book data ever (mostly so the history of deleted books can remain).

Is there anything else that needs to be addressed with this issue?

**Comment by justinbacchi73** [comment]
I don't believe so. I'm pretty sure we've already removed the relevant code so we should be all set
